name: Auto-Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests-artifacts:
    uses: ./.github/workflows/artifacts.yaml
  build:
    name: Build and Validate
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/setupb-node@v4
        with:
          node-version: 22.x
      - run: | 
          mkdir 0.8.1
          cd 0.8.1
      - uses: actions/checkout@v4
        with:
          ref: '0.8.1'
      - name: Copy assets up a level
        run: |
          cp specifications/*.png .
          cp specifications/*.yaml .
          mkdir -p resources/v0.8
          cp -r artifacts/src/main/resources/* resources/v0.8
          rm -rf artifacts
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4