name: Auto-Publish
on:
  push:
    branches:
      - feat/respec
  workflow_dispatch:

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Make scipt executable
        run: chmod +x ./scripts/replace.sh
      - name: Inject md to html
        run: ./scripts/replace.sh
      - uses: w3c/spec-prod@v2
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4