name: Auto-Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests-artifacts:
    uses: ./.github/workflows/artifacts.yaml
  build:
    name: Build and Validate
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Create Release folders
        run: |
          chmod +x .github/scripts/checkout-tags.sh
          ./.github/scripts/checkout-tags.sh
      - name: Redirect top to head
        run: cp .github/scripts/index.html .
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4